global:
  image: node:lts-alpine

  trigger:
    branch:
      - "*"
jobs:
  - name: install deps
    commands:
      - npm ci
    artifacts:
      - name: node_modules

  - name: list
    commands:
      - ls -lah
    resources:
      - name: node_modules
