global:
  image: nosana/solana:latest

  trigger:
    branch:
      - "*"
jobs:
  - name: install deps
    commands:
      - npm ci
    artifacts:
      - name: node_modules

  - name: list
    commands:
      - ls -lah
    node_modules:
      - name: node_modules
